<?php

/**
 * @file
 * Module file for agile_iit.
 */

/**
 * Implements hook_views_api().
 */
function agile_iit_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'agile_iit') . '/includes',
  );
}

/**
 * Implements hook_menu().
 */
function agile_iit_menu() {
  return array(
    'agile/iit/crop' => array(
      'file' => 'includes/callbacks.inc',
      'page callback' => 'agile_iit_crop_callback',
      'type' => MENU_CALLBACK,
      'access callback' => TRUE,
    ),
    'agile/iit/croptool' => array(
      'file' => 'includes/callbacks.inc',
      'page callback' => 'agile_iit_crop_tool_callback',
      'type' => MENU_CALLBACK,
      'access callback' => TRUE,
    ),
    'agile/iit/twoviews' => array(
      'file' => 'includes/callbacks.inc',
      'page callback' => 'agile_iit_twoviews',
      'type' => MENU_CALLBACK,
      'access callback' => TRUE,
    ),
    'agile/iit/imagecropper' => array(
      'file' => 'includes/callbacks.inc',
      'page callback' => 'agile_iit_image_cropper',
      'type' => MENU_CALLBACK,
      'access callback' => TRUE,
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function agile_iit_block_info() {

  $blocks['iit_content'] = array(
    'info' => t('IIT Comparison Tool'),
    'status' => TRUE,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'selected',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function agile_iit_block_view($delta = '') {
  module_load_include('inc', 'agile_iit', 'includes/utilities');
  $has_content = FALSE;
  switch ($delta) {
    case 'iit_content':
      $block['subject'] = t('IIT Tool');
      $block['content'] = theme('agile_iit', array());
      $has_content = TRUE;
      break;
  }
  if ($has_content) {
    return $block;
  }
}

/**
 * Implements hook_theme().
 *
 * Defines the theming capabilities provided by this module.
 */
function agile_iit_theme() {
  return array(
    'agile_iit' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/agile_iit',
    ),
    'agile_iit_crop' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/agile_iit_crop',
      'variables' => array(
        'img1_src' => NULL,
        'img2_src' => NULL,
      ),
    ),
    'agile_iit_twoviews' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/agile_iit_twoviews',
      'variables' => array(
        'img1_src' => NULL,
        'img2_src' => NULL,
      ),
    ),
  );
}
